= ESP8266Info library for ESP8266 Arduino =

== ESP8266 Module Info printing Library ==

Helps to read out essential info from ESP8266.

<br />
There are 3 main functions that help to display info about the module on which the program is running.
It might be helpful to know what is the internal configuration of the Module like - *Flash Size*,
*Type of Flash Interface*, *MAC ID* etc.
This library is designed to work with the *Serial* library. 

Hence needs initialization of the *Serial* Library before with `Serial.begin(115200);`. 

(Note: In general for ESP8266 115200 BAUD a preferred BAUD rate.)

== Example ==

```arduino
#include <ESP8266Info.h>

void setup() {
  Serial.begin(115200);
  ESP8266info();  
  ESP8266info_Wifi();
}

void loop() {
  // put your main code here, to run repeatedly:

}
```

=== Dependencies ===
 *Serial* Library
 Thread Safe: No
 Extendable: Yes

For more information about this library please visit us at
http://github.com/boseji/ESP8266Info

== License ==

Released Under creative commons license 3.0: Attribution-ShareAlike CC BY-SA

